

services:
  - serverless

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - serverless deploy -v # print the version for logging


after_success:
  - echo "nothing needs to be run"
