if: branch = master

language: node_js
node_js:
  - 10.14.4

cache:
  directories:
    - backend/node_modules

script:
  - npm install -g serverless
  - npm install
  - serverless deploy -v
  
branches:
  only:
  - master
